### ISSUE TITLE
Crash - "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by unclebacon-live** [hrfee/jfa-go#179] opened 2021-12-22 21:07 UTC
**Describe the bug**

jfa-go crashes periodically. It seemed to be better and not happen as often once I started using the internal address to Emby instead of the external but the problem is still there.

**To Reproduce**

Wasn't doing anything with it when it happened so not sure you can reproduce it on your own.

**Logs**

```
jfa-go version: 0.3.9 (0fe72b4)
Socket: /tmp/jfa-go.sock
2021/12/22 05:37:04 Using external storage
[INFO] 05:37:04  Using Emby server type
WARNING: Emby compatibility is experimental, and support is limited.
Password resets are not available.
2021/12/22 05:37:04 Failed to authenticate with Emby @ "CENSORED": Timed out

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.Exit({0xc36d20, 0x25ef4c0})
	/opt/build/exit.go:57 +0x2e5
main.start.func2()
	/opt/build/main.go:159 +0x2a
panic({0xc36d20, 0x25ef4c0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/hrfee/mediabrowser.(*MediaBrowser).Authenticate(_, {_, _}, {_, _})
	/go/pkg/mod/github.com/hrfee/mediabrowser@v0.3.5/mediabrowser.go:198 +0x87
main.start(0x0, 0x30)
	/opt/build/main.go:433 +0x2885
main.main()
	/opt/build/main.go:749 +0x3f1

```

**Configuration**

I use it with Emby. I can add more here if you need it. As stated above I switched to the internal Emby address from the external one and it made it better but still happens.

**Platform/Version**

jfa-go version: 0.3.9 (0fe72b4) docker inside unRAID.

**Comment by unclebacon-live** [comment] 2021-12-22 21:10
This was the title for the error report that was generated:
`Error: github.com/hrfee/mediabrowser.(*MediaBrowser).Authenticate:198 runtime error: invalid memory address or nil pointer dereference`

Plus I'm not sure if it's related but in the log for the jfa-go docker this gets spammed quite a bit:
```
2021/12/22 04:51:37 Failed to authenticate with updater @ "https://builds.hrfee.pw": Timed out

[ERROR] 04:51:37 updater.go:549: Failed to get latest tag (0): <nil>
```

**Comment by hrfee** [comment] 2021-12-22 23:29
I've just added slightly more detailed error reporting for when requests to Jellyfin/Emby fail, the "Timed out" message was always displayed which isn't very helpful. If you don't mind switching to unstable briefly could you try reproducing the error on it and sending the log?

Also, it looks like it crashes on start-up from the log, does it crash while it's running too? It's set up to not panic when requests to Jellyfin fail so the only thing it should do is show an error on the admin page.

The updater thing isn't a problem on your end either, my updater server is a bit broken right now which just means you won't get update notifications on the admin page.

**Comment by unclebacon-live** [comment] 2021-12-23 00:09
I don't mind switching at all and I've done so. The only issue now is that I don't know how to recreate the issue. The crash is seemingly random for me as I'll just log in to my unRAID and jfa-go will be stopped with those errors. Now, when I was using the external Emby address for jfa-go to connect to I found it crashed a lot more frequently so I'll switch back to the external address just for testing purposes to see if I can get this to happen once again. It may be a few days before I see the problem arise again.

I don't seem to have any issues with the start-up, it only crashes while it's running unless the docker is restarting on it's own and then it crashes. But I can manually restart the docker over and over and it starts just fine. And thanks for the update on the other error. I wondered if at first my DNS was blocking it but it's all good.

**Comment by hrfee** [comment] 2021-12-23 00:35
Very weird, the thing with the external address smells of network issues but there are so many weird bugs in my software that its more than likely not. For now, is there any way you can have it auto-restart when this occurs?

Updates should be fixed now, ended up being like 2 lines but I didn't have a proper way test it outside production so it took me a while lol.

**Comment by unclebacon-live** [comment] 2021-12-23 01:26
I thought network errors for sure and I would say there is still a high probability of that. Not sure why I used external at first, makes no sense. Now I just want to get this error to rear it's ugly face again and we'll hopefully see if it's me or not. I can set it to auto-restart but then I won't know when/if it crashes as above, short of checking the logs frequently. 

I see the updates are fixed. You move quick! Thanks!

**Comment by unclebacon-live** [comment] 2021-12-29 20:17
So it took a while but it's happened once again.

```
jfa-go version: git (84429a3)
Socket: /tmp/jfa-go.sock
2021/12/29 05:41:28 Using external storage
[INFO] 05:41:29  Using Emby server type
WARNING: Emby compatibility is experimental, and support is limited.
Password resets are not available.

main.go:436: Failed to authenticate with Jellyfin @ "http://INTERNAL_IP:8096" (0): Post "http://INTERNAL_IP:8096/Users/authenticatebyname": dial tcp INTERNAL_IP:8096: connect: connection refused
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.Exit({0xc290a0, 0xc0004d21c0})
	/opt/build/exit.go:57 +0x2e5
github.com/hrfee/jfa-go/logger.(*Logger).Fatalf(0xc000507e60, {0xd6824e, 0x34}, {0xc0005d5d38, 0x3, 0x3})
	/opt/build/logger/logger.go:128 +0x135
main.start(0x0, 0xf7)
	/opt/build/main.go:436 +0x2985
main.main()
	/opt/build/main.go:753 +0x451
```

Look at the dates and times from this one and the previous. I'm going to hazard a guess I've got some sort of schedule set for an update process or some other function on Wednesday mornings around 05:00 or 05:30 that is causing Emby to be unresponsive or be otherwise down long enough to cause jfa-go this issue. Your application is probably functioning as expected, especially since nobody else seems to be or has come forward with this problem.

**Comment by hrfee** [comment] 2021-12-29 21:31
Ah, yeah i'm really not sure what could be going wrong with the program that a simple post request fails like this. Hope you can figure out what the issue is, i'll close this for now but feel free to reopen if you find something.

**Closed by hrfee** 2021-12-29 21:31 UTC
